### ISSUE TITLE
does NOT support django 1.8* ?

### ISSUE THREAD

**Issue by sunjoomoon** [matthiask/django-content-editor#1]
Does this support from django 1.9 ONLY ?

**Comment by matthiask** [comment]
Hi @sunjoomoon 

Yes, at the moment this project is Django 1.9-only. The reason is that the necessary Javascript signals have only been added to Django 1.9 (formset:added and formset:removed, see https://docs.djangoproject.com/en/1.9/ref/contrib/admin/javascript/ )

The signals are used to attach custom JS to the plugin forms, for example richtext widgets (which do not like being moved around in the DOM at all): https://github.com/matthiask/django-content-editor/blob/master/content_editor/static/content_editor/content_editor.js#L163

OTOH, the relevant file django/contrib/admin/js/inlines.js is almost unchanged, so maybe you could copy the Django 1.9-version of inlines.js and inlines.min.js into your project, and things might just work with Django 1.8 as well. I think that there's nothing else in django-content-editor preventing the use of Django 1.8.

If you explore further, please report back your findings! Also, I'm happy to answer additional questions you have about django-content-editor.

Best regards, m.

**Comment by sunjoomoon** [comment]
Thanks Matthias. Understood. Having read the background, I totally agree to the philosophy. Hope this gets spreads out with more apps and users.  Will try them out as advised. Thanks.
