### ISSUE TITLE
CKEditor4 vs CKEditor5

### ISSUE THREAD

**Issue by guettli** [matthiask/django-content-editor#14]
I see you use CKEditor4. Why do you not use CKEditor5.

Because of the license of CKEditor5 (GPL, not LGPL)?

**Comment by matthiask** [comment]
To be honest, I haven't given this much thought. The main reason is that https://github.com/django-ckeditor/django-ckeditor hasn't added CKEditor 5 support yet. 

https://github.com/hvlads/django-ckeditor-5 seems to be maintained a bit better than https://github.com/pancodia/django-ckeditor5, maybe this would be an alternative? Anyway, I only use a minimal CKEditor configuration most of the time and switching to a completely different rich text editor should be possible without too much effort.

(I'm definitely interested in upgrading CKEditor but it isn't a priority to me.)

**Comment by guettli** [comment]
CKEditor 5 is GPL, not LPGL.

This means, if you create a commercial site with it, you might get legal troubles.

Are you aware if this?

See: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/support/license-and-legal.html

**Comment by matthiask** [comment]
Thanks! I think I have been aware of this in the past but I have forgotten it (despite you mentioning it in the issue description already).

Yes, CKEditor 5 being GPL'd is a good reason for NOT using it in feincms3. It would probably be possible to create a GPL'd feincms3-ckeditor5 package and move https://github.com/matthiask/feincms3/blob/main/feincms3/static/feincms3/plugin_ckeditor.js there but it's still a legal risk according to my understanding of the GPL (https://greendrake.info/#nfy0)

Anyway, the point above regarding switching rich text editors still stands. Since CKEditor 4 is well maintained this isn't an issue now (I think) and will be relatively painless to solve in the future.

**Comment by guettli** [comment]
Thank you for the link to https://greendrake.info/#nfy0
