### ISSUE TITLE
BUG - Toggling between 'Source' view and 'Rich Text' view resets source changes

### ISSUE THREAD

**Issue by MihaiChirculete** [matthiask/django-content-editor#21]
Steps to reproduce:
1. Add some text in the 'Rich Text' window
2. Click on the 'Source' button which enables the html view
3. Between the brackets of the earlier added paragraph add some rules such as 'class' like so: <p class='test'>Bla bla bla</p>
4. Click on 'Source' button again, now the html view is replaced by the document editor view
5. Click on 'Source' once again, now the html view is visible again and the <p> tag lost it's class

**Expected behaviour:** Changes made to source persist
**Actual behaviour** Clicking the 'Source' button resets changes

**Comment by matthiask** [comment]
Thanks for the report. I think this happens because CKEditor automatically filters the allowed tags according so some allowlist which can be configured in principle. Maybe you can search the CKEditor docs or the django-ckeditor issue tracker for ways how to configure CKEditor so that it works better for you, see e.g. https://github.com/django-ckeditor/django-ckeditor/issues/664

I cannot help much because I only ever use a stripped down rich text field, see https://django-content-editor.readthedocs.io/en/latest/#about-rich-text-editors for the reasoning.

**Comment by matthiask** [comment]
I'm going to close this as works-as-intended; if it were a bug it weren't a bug with django-content-editor but with the rich text widget used.
